# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
<<<<<<< HEAD
run ShanghaiTonightGuide::Application
=======
run Rails3BootstrapDeviseCancan::Application
>>>>>>> new Rails app generated by Rails Apps Composer gem
