# Be sure to restart your server when you modify this file.

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
<<<<<<< HEAD
ShanghaiTonightGuide::Application.config.secret_token = '29681aeb5fe036233cd37a94f1cd39a1c01999600530c7664e2e12f975028986534b6f1c83abae0a79f8bcbbebff571e64f92f414ad38b659252e11a73d48706'
=======
Rails3BootstrapDeviseCancan::Application.config.secret_token = 'a6cd68af2c0c93e2f0bd4c576aab509f59b7ae839d02018caa4c8ce3cc46ea012fdc4f1dc93bbb14137bc646fb697907e9649260d02b77eed838717d20dff479'
>>>>>>> new Rails app generated by Rails Apps Composer gem
