# Be sure to restart your server when you modify this file.

<<<<<<< HEAD
ShanghaiTonightGuide::Application.config.session_store :cookie_store, key: '_shanghai_tonight_guide_session'
=======
Rails3BootstrapDeviseCancan::Application.config.session_store :cookie_store, key: '_rails3-bootstrap-devise-cancan_session'
>>>>>>> new Rails app generated by Rails Apps Composer gem

# Use the database for sessions instead of the cookie-based default,
# which shouldn't be used to store highly confidential information
# (create the session table with "rails generate session_migration")
<<<<<<< HEAD
# ShanghaiTonightGuide::Application.config.session_store :active_record_store
=======
# Rails3BootstrapDeviseCancan::Application.config.session_store :active_record_store
>>>>>>> new Rails app generated by Rails Apps Composer gem
