# Load the rails application
require File.expand_path('../application', __FILE__)

# Initialize the rails application
<<<<<<< HEAD
ShanghaiTonightGuide::Application.initialize!
=======
Rails3BootstrapDeviseCancan::Application.initialize!
>>>>>>> new Rails app generated by Rails Apps Composer gem
